name: data
on:
  schedule:
    # Runs every day at 6:48 AM UTC/1:48 AM PT/4:48 AM ET
    - cron: 48 6 * * *
  workflow_dispatch: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: ${{ secrets.TEST_ENVIRONMENT }}
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Pull from main
        run: |-
          git pull
      - name: Fetch current-federal
        run: curl -fsSL -o "current-federal-${TEST_ENV}.csv" "https://getgov-${TEST_ENV}.app.cloud.gov/api/v1/get-report/current-federal"
      - name: Fetch current-full
        run: curl -fsSL -o "current-full-${TEST_ENV}.csv" "https://getgov-${TEST_ENV}.app.cloud.gov/api/v1/get-report/current-full"
      - name: Commit updated data
        run: |
          git config user.name "botgov"
          git config user.email "help@get.gov"
          git add "current-federal-${TEST_ENV}.csv" "current-full-${TEST_ENV}.csv"
          git commit -m "Flat: latest data ($(date -u +%FT%TZ))" || exit 0
          git push
